name: Docker Image and Docker Hub Push CI

on:
  workflow_run:
    workflows: ["Python application"]
    types:
      - completed

jobs:

  notify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ofarmash/handsensor-flask:${{ github.sha:0:1}}.${{ github.sha:1:2}}.${{ github.sha:2:3}}.${{ github.sha:3:4}}.${{ github.run_number }}
          
